[package]
name = "iroh-metrics"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0/MIT"
readme = "README.md"
description = "Iroh metrics"
repository = "https://github.com/n0-computer/iroh"

[dependencies]
tracing = "0.1.33"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
tracing-opentelemetry = "0.18"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.11.0", features = ["tonic"] }
metrics = "0.20.1"
metrics-util = "0.14"
metrics-exporter-prometheus = { version = "0.11", features = ["push-gateway"]}
tonic = { version = "0.8", optional = true }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "process"] }
prometheus-client = "0.18.0"
reqwest = { version = "0.11.10", features = ["rustls-tls"], default-features = false}
config = "0.13.1"
iroh-util = { path = "../iroh-util" }
names = { version = "0.14.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4.0"
async-trait = "0.1.57"
console-subscriber = { version = "0.1.7", optional = true }
paste = "1.0.9"

[dependencies.libp2p]
version = "0.50"
default-features = false
features = [
  "gossipsub",
  "kad",
  "identify",
  "ping",
  "mdns",
  "noise",
  "yamux",
  "tcp",
  "dns",
  "mplex",
  "request-response",
  "websocket",
  "serde",
  "metrics",
  "relay",
  "dcutr",
  "autonat",
  "tokio",
] 
optional = true

[features]
default = ["rpc-grpc"]
rpc-grpc = ["tonic"]
gateway = []
resolver = []
bitswap = []
store = []
p2p = ["libp2p"]

# requires setting RUSTFLAGS="--cfg tokio_unstable"
tokio-console = ["tokio/tracing", "console-subscriber"]
