[package]
name = "iroh-metrics"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0/MIT"
readme = "README.md"
description = "Iroh metrics"
repository = "https://github.com/n0-computer/iroh"
rust-version = "1.63"

[dependencies]
async-trait = "0.1.57"
config = "0.13.1"
console-subscriber = { version = "0.1.7", optional = true }
iroh-util = { path = "../iroh-util" }
lazy_static = "1.4.0"
names = { version = "0.14.0", default-features = false }
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.11.0", features = ["tonic"] }
paste = "1.0.9"
prometheus-client = "0.18.0"
reqwest = { version = "0.11.10", features = ["rustls-tls"], default-features = false}
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "process"] }
tonic = { version = "0.8", optional = true }
tracing = "0.1.33"
tracing-opentelemetry = "0.18"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }

[dependencies.libp2p]
version = "0.50"
default-features = false
features = [
  "gossipsub",
  "kad",
  "identify",
  "ping",
  "mdns",
  "noise",
  "yamux",
  "tcp",
  "dns",
  "mplex",
  "request-response",
  "websocket",
  "serde",
  "metrics",
  "relay",
  "dcutr",
  "autonat",
  "tokio",
] 
optional = true

[features]
default = ["rpc-grpc"]
rpc-grpc = ["tonic"]
gateway = []
resolver = []
bitswap = []
store = []
p2p = ["libp2p"]

# requires setting RUSTFLAGS="--cfg tokio_unstable"
tokio-console = ["tokio/tracing", "console-subscriber"]
