[package]
name = "iroh-metrics"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0/MIT"
readme = "README.md"
description = "Iroh metrics"
repository = "https://github.com/n0-computer/iroh"

[dependencies]
tracing = "0.1.33"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
tracing-opentelemetry = "0.17.2"
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.10.0", features = ["tonic"] }
metrics = "0.18.1"
metrics-util = "0.12"
metrics-exporter-prometheus = { version = "0.9", features = ["push-gateway"]}
tonic = { version = "0.7.2", optional = true }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "process"] }
prometheus-client = "0.17.0"
reqwest = { version = "0.11.10", features = ["rustls-tls"], default-features = false}
config = "0.13.1"
iroh-util = { path = "../iroh-util" }
names = { version = "0.13.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }

[features]
default = ["rpc-grpc"]
rpc-grpc = ["tonic"]