[bans]
multiple-versions = "allow"
deny = ["aws-lc", "aws-lc-rs", "aws-lc-sys", "native-tls", "openssl"]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSL-1.0",                        # BOSL license
    "MIT",
    "Unicode-3.0",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[advisories]
ignore = [
  "RUSTSEC-2023-0089", # unmainatined: postcard -> heapless -> atomic-polyfill
]
